#!/bin/bash

echo "═══════════════════════════════════════════════════"
echo "  🐛 QUICK DEBUG GUIDE"
echo "═══════════════════════════════════════════════════"
echo ""
echo "📱 TO DEBUG MOBILE APP IN CHROME:"
echo ""
echo "1. Start the app:"
echo "   cd mobile && npm start"
echo ""
echo "2. Open Expo Go on your phone"
echo ""
echo "3. Enable Remote Debugging:"
echo "   - Shake device (or Cmd+D on iOS simulator)"
echo "   - Select 'Debug Remote JS'"
echo ""
echo "4. Chrome DevTools will open automatically"
echo "   Or go to: chrome://inspect"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📊 VIEW LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend logs:"
echo "  tail -f /tmp/backend.log"
echo ""
echo "Mobile logs:"
echo "  tail -f /tmp/mobile_*.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔍 CHROME DEVTOOLS TABS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Console Tab:"
echo "  - See all console.log() output"
echo "  - View JavaScript errors"
echo ""
echo "Network Tab:"
echo "  - See all HTTP requests"
echo "  - View request/response data"
echo "  - Check API calls"
echo ""
echo "Application Tab:"
echo "  - View AsyncStorage data"
echo "  - Check stored tokens"
echo ""
echo "Sources Tab:"
echo "  - Set breakpoints"
echo "  - Step through code"
echo ""
echo "═══════════════════════════════════════════════════"
echo ""
echo "💡 Full guide: mobile/DEBUG_GUIDE.md"
echo ""

